(function() {
    function Fixture() {
        var Fixture = {};
        
        var breakup = {
            reference: firebase.database().ref().child('breakup'),
            library: ["Look, there's something I've been thinking about. I think we should break up.", "I'm sorry, this isn't working out. I want to break up. It's not you, it's me.", "I think we should break up. I'm sorry, I just don't have space in my life for a romantic relationship right now. It's not fair to you.", "I want to break up. I really need to focus on my career for a while.", "I think we should spend some time apart. It's not fair to my kids. I haven't been spending enough time with them.", "I think we should split up. When we first started dating everything was magic and now I feel like we've lost that spark.", "Something has been bugging me recently. I love you. I'll always love you in a way but I've realized that I'm no longer IN love with you. So I think that we should break up.", "You're a great person but I don't think you're the right person. I think we should break up.", "I've been trying to decide if I'm ready to take this relationship to the next level and I'm not. I'm not sure if I ever will so I think it's best if we just break up. It's not fair to either of us to stay in this any longer.", "I've been waiting for you to show me that you really care and I'm tired of waiting. It's over between us.", "I feel like we're stuck in neutral and that this relationship isn't progressing. I can't stay in a situation like this. I think we should break up."]
        };
        
        var compliment = {
            reference: firebase.database().ref().child('compliment'),
            library: ["Your perspective is refeshing.", "You have impeccable manners.", "You are one smart cookie.", "I like your style.", "You have the best laugh. I can hear it right now thinking about it.", "You're an awesome friend.", "On a scale from 1 to 10, you're an 11.", "You have a great sense of humor.", "I wish everyone were as good a friend as you.", "You bring out the best in other people.", "Your ability to recall random factoids at just the right time is impressive.", "You're a great listener.", "You were cool way before hipsters were cool.", "Hanging out with you is always a blast.", "You have the best ideas.", "You always know just what to say.", "I'll bet you could survive a zombie apocalypse.", "You're more fun than bubble wrap.", "You're great at figuring stuff out.", "You're gorgeous -- and that's the least interesting thing about you, too.", "", "", "", "When you make up your mind about something, nothing stands in your way.", "I bet you do the crossword puzzle in ink.", "I disagree with anyone who disagrees with you.", "With your creative wit, I'm sure you could come up with better compliments than me.", "I love the way you type.", "You're cooler than Pirates and Ninjas combined.", "You could probably lead a rebellion.", "Your voice is more soothing than Morgan Freeman's.", "You are more fun than a Japanese steakhouse."]
        };
        
        var excuseToLeave = {
            reference: firebase.database().ref().child('excuseToLeave'),
            library: ["My roommates made dinner and it's time to eat.", "My roommate is about to leave and I need to talk to him before he goes.", "I've got to talk to some coworkers about a project we're working on before it gets too late.", "I'm swamped with work and should really get back to the grind.", "I need to change my laundry.", "I just realized I left my card at the bar last night.", "I'm meeting a friend for coffee.", "My mom is calling me right now and this could take a while.", "My friend who lives in Europe is calling! We never speak. Sorry, I've got to go. I hope you understand.", "Sorry, my boss is calling.", "My battery's running low, so I'm going to hop off. Talk to you again soon!", "Wow, I can't believe it's gotten late so quickly. Do you mind if I log off and finish my to-do list for the day?", "Hey, sorry but I've got to get the gym before it closes. Talk to you again soon!", "My dog is going crazy right now. I need to take him for a walk before he starts tearing up the furniture.", "Just saw the bat signal. Gotta go.", "It's my turn to make dinner tonight for my roommates. I'd better get started.", "It's movie night with the roommates. I should go join them.", "The fire alarm just went off in my building. It's probably a false alarm but I've gotta go"]
        };
        
        var joke = {
            reference: firebase.database().ref().child('joke'),
            library: ["What weighs more, 100 pounds of gold or 100 pounds of feathers?\n \nThe feathers, because you also have to carry the weight of what you did to those poor birds.", "Why is six afraid of seven? \n \nBecause seven 'ate' nine", "How can you tell you have a really bad case of acne? \n \nWhen the blind try to read your face.", "What's the worst part of being lonely? \n \nPlaying Frisbee", "Why did the shark keep swimming in a circle? \n \nIt had a nosebleed.", "Did you hear about that naked woman who robbed a bank? Nobody could remember her face.", "How can you tell that a crab is drunk? \n \nIt walks forwards.", "Why do cows wear bells? \n \nBecause their horns don't work.", "A doctor tells a patient that they have cancer and Alzheier's. The patient frowns and says, 'Well, at least I don't have cancer.'", "I asked my North Korean friend how it was to live in North Korea. He said he can't complain.", "Why did the physics teacher break up with the biology teacher? \n \nBecause there was no chemistry.", "Guess who I bumped into on the way to the eye doctor! \n \nEverybody.", "WHat's blue and smells like red paint? \n \nBlue paint.", "What happens when you cross a snowman and a vampire? \n \nYou get a frostbite.", "My friend thinks he is smart. He told me an onion is the only food that makes you cry, so I threw a coconut at his face.", "Why does Humpty Dumpty love autumn? \n \nBecause Humpty Dumpty had a great fall.", "A teacher asked their student, 'If I have fiive bottles in one hand and six bottles in the other, what do I have?' The student replied, 'A drinking problem.'", "What do you call a woman with a peg leg? \n \nEileen", "What starts with E, ends with E, and has only 1 letter in it? \n \nEnvelope", "How many snowboarders does it take to screw in a lightbulb? \n \n50: 3 to die trying, 1 to actually pull it off, and 46 others to say, 'Pshhh, I could do that.'", "My friend told me he had the body of a Greek god. I had to explain to him that Buddha is not Greek.", "Why did the golferwear two pairs of pants? \n \nIn case he got a hole in one", "Why did the can crusher quit its job? \n \nBecause it was soda pressing", "What starts with a P, ends with an E, and has a 1,000 letters? \n \nPost office.", "A wife said to her husband, 'Honey, I look fat. Can you give me a compliment?' to which the husband said, 'Sure, you have perfect eyesight.'"]
        };
        
        var smackTalk = {
            reference: firebase.database().ref().child('smackTalk'),
            library: ["Your hair looks STUPID.", "You loook like you fell off the ugly tree and hit every branch on the way down.", "Your mother was a hamster and your father smelled of elderberries.", "Has anyone ever told you that you look like a partially full burlap sack with a face drawn on it?", "You know the saying, 'you are what you eat'? What the hell did you eat?!", "Your face looks like it caught fire and someone put it out with a hammer.", "Your face makes onions cry.", "You are the reason they put instructions on shampoo.", "Every enemy I've met, I've annihilated.",  "You look like I need a drink.", "If I had a dollar for every brain you don't have, I'd have a dollar.", "I'd agree with you but then we'd both be wrong.", "The jerk store called and they're all out of you.", "You think you're too cool for school. Well I've got a newsflash for you, Walter Cronkite. You aren't.", "Hold that thought real quick, let me turn on the part of my brain that cares.", "Shut up, idiot head face.", "I'm about to school you like fish.", "Did you hear the bell ring? Someone is about to get served.", "Just shut up and have my fries ready at the window.", "If my dog's butt looked like your face, my dog would look like a normal dog."]
        };
        
        var subjectChange  = {
            reference: firebase.database().ref().child('subjectChange'),
            library: ["Man, it's so cold outside today. I think I even saw a politician with his hands in his own pockets.", "I can't believe I forgot to go to the gym today. That's seven years in a row now.", "Have you noticed that in the 21st century deleting your history can be as important as making it?", "Have you read any good books lately?", "Have you been to the movies lately?", "What did you do last weekend?", "Do you have anything fun planned for the weekend?", "Are you excited for the upcoming holiday?", "What kind of music do you listen to?", "If you could travel anywhere in the world, where would you go?", "If you could have any superpower what would it be?", "My friend and I were arguing earlier about something and I want to know what you think. Would you rather be able to fly or be invisible?", "What was your dream job growing up?", "Hey, do you want to hear a joke? \n" + joke.library[Math.floor(Math.random() * joke.library.length)]]
        };
        
        Fixture.getFixture = function(string) {
            return eval(string);
        };
        
        return Fixture;
    };
    
    angular
        .module('awkwardAssist')
        .service('Fixture', [Fixture]);
    
})();